-- AlterTable
ALTER TABLE "Titan" ADD COLUMN IF NOT EXISTS "cardioIndex" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Titan" ADD COLUMN IF NOT EXISTS "lastPowerCalcAt" TIMESTAMP(3);
ALTER TABLE "Titan" ADD COLUMN IF NOT EXISTS "mrvAdherence" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE "Titan" ADD COLUMN IF NOT EXISTS "powerRating" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Titan" ADD COLUMN IF NOT EXISTS "strengthIndex" DOUBLE PRECISION NOT NULL DEFAULT 0;
