version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser", "nodejs", "vitest"]
  module_system = "esm"
  ts_config_path = "tsconfig.json"

[[analyzers]]
name = "test-coverage"
enabled = true

exclude_patterns = [
  "node_modules/**",
  ".next/**",
  "tests/**"
]
