
import { Session, AppSettings, BlockType } from '../types';


export const IntegrationService = {

    /**
     * Determines if a session is primarily Cardio (Intervals) or Strength (Hevy)
     */
    detectSessionType: (session: Session): 'CARDIO' | 'STRENGTH' => {
        let cardioScore = 0;
        let strengthScore = 0;

        session.blocks.forEach(block => {
            if (block.type === BlockType.STATION && block.exercises) {
                block.exercises.forEach(ex => {
                    // Check if reps are time-based (string containing 'min' or 'sec')
                    const isTimeBased = ex.sets.some(s => typeof s.reps === 'string' && (s.reps.includes('min') || s.reps.includes('sec')));

                    // Or if instructions mention Z1-Z5
                    const isZone = ex.name.includes('Zone') || (ex.instructions || []).some(i => i.includes('HR') || i.includes('Zone'));

                    if (isTimeBased || isZone) cardioScore++;
                    else strengthScore++;
                });
            }
        });

        return cardioScore > strengthScore ? 'CARDIO' : 'STRENGTH';
    },

    /**
     * Uploads the completed session to Intervals.icu as a structured workout.
     */
    async uploadToIntervals(session: Session, settings: AppSettings): Promise<boolean> {
        if (!settings.intervalsApiKey || !settings.intervalsAthleteId) throw new Error("Missing Intervals Credentials");

        // 1. Build Workout Text (Intervals.icu Markup)
        let workoutText = "";

        session.blocks.forEach(block => {
            if (block.type === BlockType.WARMUP) {
                workoutText += "Warmup\n";
                block.exercises?.forEach(ex => {
                    // Default warmup assumption: 50% intensity
                    workoutText += `- 10m 50% ${ex.name}\n`;
                });
                workoutText += "\n";
            }
            else if (block.type === BlockType.STATION) {
                workoutText += "Main Set\n";
                block.exercises?.forEach(ex => {
                    ex.sets.forEach((set, i) => {
                        // Parse reps: "4 min" -> "4m"
                        let duration = "5m"; // Default
                        if (typeof set.reps === 'string') {
                            if (set.reps.includes('min')) duration = set.reps.replace(' min', 'm');
                        }

                        workoutText += `- ${duration} Z3 ${ex.name} (Set ${i + 1})\n`;
                    });
                });
                workoutText += "\n";
            }
        });

        // 2. Prepare Payload
        const payload = {
            category: "WORKOUT",
            start_date_local: new Date().toISOString(),
            name: session.name,
            description: `Generated by IronForge.\n\n${session.zoneName || ''}`,
            type: "Ride", // Defaulting to Ride, could be Run
            workout: workoutText
        };

        // 3. Send
        try {
            const response = await fetch(`https://intervals.icu/api/v1/athlete/${settings.intervalsAthleteId}/events`, {
                method: 'POST',
                headers: {
                    'Authorization': `Basic ${btoa('API_KEY:' + settings.intervalsApiKey)}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error("Intervals API Upload Failed");
            return true;
        } catch (e) {
            console.error(e);
            return false;
        }
    },

    /**
     * Uploads the completed session to Hevy (Simulated / API Structure).
     */
    async uploadToHevy(session: Session, settings: AppSettings): Promise<boolean> {
        if (!settings.hevyApiKey) throw new Error("Missing Hevy Credentials");

        // Map Internal Session to Hevy Payload Structure
        const workoutExercises = [];

        for (const block of session.blocks) {
            if (block.exercises) {
                for (const ex of block.exercises) {
                    const sets = ex.sets.map((s, idx) => ({
                        type: "normal",
                        weight_kg: s.weight || 0,
                        reps: typeof s.reps === 'number' ? s.reps : (s.completedReps || 0),
                        rpe: s.isPrZone ? 10 : 8
                    }));

                    workoutExercises.push({
                        exercise_template_id: null, // Hevy needs IDs, we send name as fallback/note
                        title: ex.name,
                        notes: ex.instructions?.join('\n'),
                        sets: sets
                    });
                }
            }
        }

        const payload = {
            workout: {
                title: session.name,
                notes: "IronForge Titan Log",
                start_time: new Date().toISOString(),
                exercises: workoutExercises
            }
        };

        // Simulated API Call (Since Hevy API access is restricted)
        console.log("HEVY PAYLOAD PREPARED:", payload);

        // In a real scenario with a valid key:
        /*
        const response = await fetch('https://api.hevyapp.com/v1/workouts', {
            method: 'POST',
            headers: { 'hevy-api-key': settings.hevyApiKey },
            body: JSON.stringify(payload)
        });
        */

        // Simulate network delay and success
        await new Promise(r => setTimeout(r, 1000));
        return true;
    }
};
