import { GoalPriorityEngine } from './GoalPriorityEngine';
import { WardensManifest, SystemMetrics, MacroPhase } from '@/types/goals';
import { WorkoutDefinition } from '@/types/training';

export interface CoachingStrategy {
    phase: MacroPhase;
    primaryFocus: string;
    recommendedWorkouts: WorkoutDefinition[];
    contextSummary: string;
    metrics: SystemMetrics;
}

export class OracleService {
    /**
     * Generates a deterministic training strategy based on the user's current metrics and goals.
     * This "Grounds" the LLM with hard data from the GoalPriorityEngine.
     */
    static generateTrainingStrategy(
        manifest: WardensManifest,
        metrics: SystemMetrics
    ): CoachingStrategy {
        // 1. Determine optimal phase
        const phase = GoalPriorityEngine.selectPhase(manifest, metrics);

        // 2. Identify primary goal
        const primaryFocus = manifest.goals[0]?.goal || 'FITNESS';

        // 3. Select top 3 workouts
        // We calculate a default "Fresh" budget if one isn't passed, but here we just pass
        // a derived budget concept. GoalPriorityEngine.selectWorkout expects DailyResourceBudget.
        // We'll estimate available budget based on readiness (TSB).
        const readinessFactor = Math.max(0.5, Math.min(1.2, (metrics.tsb + 30) / 60)); // -30 TSB = 0.5, +30 TSB = 1.0 (approx)

        const budget = {
            cns: 50 * readinessFactor,
            muscular: 50 * readinessFactor,
            metabolic: 50 * readinessFactor
        };

        const recommendedWorkouts = GoalPriorityEngine.selectWorkout(
            manifest,
            phase,
            budget,
            undefined, // No heatmap for now
            undefined, // No prefs
            true // Allow budget override for recommendations (aspirational)
        );

        // 4. Generate Context Summary for the LLM
        // This string will be injected into the System Prompt.
        const contextSummary = `
TRAINING STRATEGY (Generated by GoalPriorityEngine):
- Current Phase: ${phase}
- Primary Goal: ${primaryFocus}
- Weekly Target: ${metrics.ctl} CTL (Fitness)
- Actionable Recommendation: ${recommendedWorkouts[0]?.name || "Active Recovery"}
`;

        return {
            phase,
            primaryFocus,
            recommendedWorkouts,
            contextSummary,
            metrics
        };
    }
}
