import React from 'react';
import Link from 'next/link';
import { Dumbbell, Brain, Users, Trophy, ArrowRight, Zap, Shield, BarChart3 } from 'lucide-react';

export default function MarketingPage() {
    return (
        <div className="min-h-screen bg-zinc-950 text-white font-sans">
            {/* Hero */}
            <section className="relative overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-br from-indigo-900/30 via-transparent to-orange-900/20" />
                <div className="absolute -top-40 -right-40 w-96 h-96 bg-indigo-600 rounded-full blur-[150px] opacity-30" />

                <div className="relative max-w-6xl mx-auto px-6 py-24 text-center">
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-orange-900/30 border border-orange-700/50 rounded-full text-orange-400 text-sm font-bold mb-8">
                        <Zap className="w-4 h-4" /> Hevy Users: Upgrade Your Game
                    </div>

                    <h1 className="text-5xl md:text-7xl font-black tracking-tight mb-6 bg-gradient-to-r from-white via-indigo-200 to-orange-200 bg-clip-text text-transparent">
                        Train Like a Titan.
                    </h1>
                    <p className="text-xl text-zinc-400 max-w-2xl mx-auto mb-12">
                        IronForge is an AI-powered strength training RPG that transforms your workouts into epic quests. What other apps do with spreadsheets, we do with intelligence.
                    </p>

                    <div className="flex flex-col sm:flex-row justify-center gap-4">
                        <Link href="/login" className="px-8 py-4 bg-indigo-600 text-white font-bold rounded-xl hover:bg-indigo-500 shadow-lg shadow-indigo-900/40 flex items-center justify-center gap-2">
                            Start Your Quest <ArrowRight className="w-5 h-5" />
                        </Link>
                        <Link href="#features" className="px-8 py-4 bg-zinc-800 border border-zinc-700 text-zinc-300 font-bold rounded-xl hover:bg-zinc-700">
                            See Features
                        </Link>
                    </div>
                </div>
            </section>

            {/* Features */}
            <section id="features" className="py-24 bg-zinc-900/50">
                <div className="max-w-6xl mx-auto px-6">
                    <h2 className="text-3xl font-black text-center mb-4">Why IronForge?</h2>
                    <p className="text-zinc-500 text-center mb-16 max-w-xl mx-auto">Features that Hevy can&apos;t match.</p>

                    <div className="grid md:grid-cols-3 gap-8">
                        <FeatureCard
                            icon={<Brain className="w-8 h-8" />}
                            title="AI Coach (The Oracle)"
                            description="Get intelligent weekly programs generated by Gemini 2.5 Flash. Adjusts to your recovery, goals, and equipment."
                            color="indigo"
                        />
                        <FeatureCard
                            icon={<Trophy className="w-8 h-8" />}
                            title="Deep Gamification"
                            description="Level up your Titan, earn Gold, unlock gear, battle bosses, and compete on leaderboards. Training has never been this fun."
                            color="yellow"
                        />
                        <FeatureCard
                            icon={<BarChart3 className="w-8 h-8" />}
                            title="Cross-Domain Fitness"
                            description="Integrates with Intervals.icu for physiological metrics (CTL, ATL, TSB). Cardio and strength in one system."
                            color="blue"
                        />
                    </div>
                </div>
            </section>

            {/* Social Proof / CTA */}
            <section className="py-24">
                <div className="max-w-3xl mx-auto px-6 text-center">
                    <h2 className="text-3xl font-black mb-6">Ready to Forge Your Legend?</h2>
                    <p className="text-zinc-400 mb-8">Join thousands of Titans who have upgraded from basic logging to intelligent training.</p>
                    <Link href="/login" className="inline-flex items-center gap-2 px-10 py-5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-bold rounded-xl text-lg hover:from-indigo-500 hover:to-purple-500 shadow-xl shadow-indigo-900/30">
                        Enter the Forge <ArrowRight className="w-5 h-5" />
                    </Link>
                </div>
            </section>

            {/* Footer */}
            <footer className="py-8 border-t border-zinc-800 text-center text-zinc-600 text-sm">
                <p>&copy; {new Date().getFullYear()} IronForge. Train Smarter. Level Up.</p>
            </footer>
        </div>
    );
}

function FeatureCard({ icon, title, description, color }: { icon: React.ReactNode; title: string; description: string; color: string }) {
    const colorClasses: Record<string, string> = {
        indigo: 'bg-indigo-900/30 border-indigo-700/50 text-indigo-400',
        yellow: 'bg-yellow-900/30 border-yellow-700/50 text-yellow-400',
        blue: 'bg-blue-900/30 border-blue-700/50 text-blue-400',
    };

    return (
        <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8 hover:border-zinc-700 transition-colors">
            <div className={`w-14 h-14 rounded-xl flex items-center justify-center mb-6 border ${colorClasses[color]}`}>
                {icon}
            </div>
            <h3 className="text-xl font-bold text-white mb-3">{title}</h3>
            <p className="text-zinc-400 text-sm leading-relaxed">{description}</p>
        </div>
    );
}
