name: 🎮 Feature Request
description: New feature for IronForge (agent-optimized)
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Use this template for new features. Agents will use this to understand scope.

  - type: textarea
    id: context
    attributes:
      label: 📋 Context
      description: Why is this needed? Link to roadmap item if exists.
      placeholder: |
        **Roadmap:** [roadmap.md#guild-territories](../roadmap.md)
        **User Problem:** Players want territory control mechanics
        **Business Value:** Increases retention via social competition
    validations:
      required: true

  - type: textarea
    id: spec
    attributes:
      label: 📄 Specification
      description: Link to detailed spec or describe the feature
      placeholder: |
        **Spec:** [specs/guild-territories.md](specs/guild-territories.md)
        
        OR inline description:
        - Feature X should...
        - Users can...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      description: Checkboxes that define "done"
      placeholder: |
        - [ ] Territory claiming works via guild action
        - [ ] Weekly contest cycle implemented
        - [ ] UI shows territory map
        - [ ] Unit tests pass
        - [ ] E2E test covers happy path
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: 🔧 Technical Notes
      description: Architecture hints, constraints, patterns to follow
      placeholder: |
        **Pattern:** Use existing GuildService
        **Database:** Add Territory model to schema.prisma
        **API:** Server action in src/actions/guild/
        **Avoid:** Don't duplicate logic from existing combat system

  - type: textarea
    id: files
    attributes:
      label: 📁 Files Affected
      description: Expected files to create/modify (helps scope estimation)
      placeholder: |
        **Create:**
        - `src/actions/guild/territory.ts`
        - `src/components/guild/TerritoryMap.tsx`
        
        **Modify:**
        - `prisma/schema.prisma`
        - `src/services/GuildService.ts`

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dependencies
      description: Issues that must be completed first
      placeholder: |
        - Blocked by: #XX (Guild system)
        - Related: #YY (Map UI component)

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: input
    id: roi
    attributes:
      label: ROI Score
      description: Value score from 1.0-5.5
      placeholder: "4.6"

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - S (< 1 day)
        - M (1-3 days)
        - L (3-7 days)
        - XL (> 1 week)
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      options:
        - Game
        - Infra
        - Bio
        - Social
        - Commerce
    validations:
      required: true
