name: ðŸ”§ Infrastructure Task
description: DevOps, CI/CD, database, or platform work
title: "[INFRA] "
labels: ["infrastructure"]
body:
  - type: markdown
    attributes:
      value: |
        ## Infrastructure Task
        For DevOps, database migrations, CI/CD, monitoring, etc.

  - type: textarea
    id: context
    attributes:
      label: ðŸ“‹ Context
      description: Why is this infrastructure work needed?
      placeholder: |
        **Problem:** CI pipeline takes 15 minutes
        **Impact:** Slows down development velocity
        **Trigger:** Multiple PRs blocked waiting for CI
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: ðŸŽ¯ Scope
      description: What exactly needs to be done
      placeholder: |
        - Add parallel test execution in CI
        - Cache node_modules between runs
        - Split E2E tests into shards
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: âœ… Acceptance Criteria
      description: How to verify this is done
      placeholder: |
        - [ ] CI completes in < 5 minutes
        - [ ] All existing tests still pass
        - [ ] No increase in flaky test rate
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: ðŸ“ Files Affected
      description: Infrastructure files to modify
      placeholder: |
        - `.github/workflows/ci-cd.yml`
        - `playwright.config.ts`
        - `vitest.config.ts`

  - type: textarea
    id: risks
    attributes:
      label: âš ï¸ Risks & Rollback
      description: What could go wrong, how to revert
      placeholder: |
        **Risks:**
        - Parallel tests may have shared state issues
        
        **Rollback:**
        - Revert to previous ci-cd.yml

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - critical
        - high
        - medium
        - low
    validations:
      required: true

  - type: input
    id: roi
    attributes:
      label: ROI Score
      placeholder: "4.5"

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - S (< 1 day)
        - M (1-3 days)
        - L (3-7 days)
        - XL (> 1 week)
    validations:
      required: true
