import { IntervalsWellness } from "@/types";
// We will need to define CardioLog and ExerciseLog types if they aren't auto-generated by Prisma yet,
// or import them from @prisma/client once generated.
// For now, we define interfaces matching the schema.

export type OracleDecreeType = "BUFF" | "DEBUFF" | "NEUTRAL";

export interface OracleDecree {
  type: OracleDecreeType;
  label: string; // e.g. "Decree of Rest"
  description: string; // e.g. "The Titan demands rest to heal."
  effect?: {
    stat?: string; // e.g. "strength"
    modifier?: number; // e.g. 0.8
    xpMultiplier?: number; // e.g. 1.2
  };
}

export interface DecreeContext {
  wellness: IntervalsWellness;
  recentVolume: number; // calculated from last 7 days maybe?
  recentLoad: number; // calculated from last 7 days
  history: {
    strength: any[]; // ExerciseLog[] - using any for now to avoid circular deps before generation
    cardio: any[]; // CardioLog[]
  };
}
