/**
 * Quarantine & Debt Sync for CI Doctor God Mode.
 * Moves flaky tests to quarantine, creates GH issues, and updates DEBT.md.
 */
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

function getPrNumber(): string {
    try {
        return execSync('gh pr view --json number -q ".number"').toString().trim();
    } catch (e) {
        return '';
    }
}

function createDebtIssue(testPath: string, prNumber: string): string {
    const title = `🚨 [FLAKY TEST] ${path.basename(testPath)}`;
    const body = `Test was quarantined during CI run for PR #${prNumber}.\n\nPath: ${testPath}\n\nThis issue was automatically generated by CI Doctor God Mode.`;

    try {
        const output = execSync(`gh issue create --title "${title}" --body "${body}" --label "technical-debt,flaky-test"`).toString().trim();
        const issueUrl = output.match(/https:\/\/github\.com\/[^\/]+\/[^\/]+\/issues\/(\d+)/);
        return issueUrl ? issueUrl[0] : output;
    } catch (e) {
        console.error('Failed to create GitHub issue:', e);
        return '';
    }
}

function updateDebtFile(testPath: string, issueUrl: string) {
    const debtFilePath = path.resolve('DEBT.md');
    if (!fs.existsSync(debtFilePath)) return;

    const date = new Date().toISOString().split('T')[0];
    const newEntry = `| ${date} | ${testPath} | Flaky test quarantined. Fixed required. | @infrastructure | [Issue](${issueUrl}) |\n`;

    try {
        const content = fs.readFileSync(debtFilePath, 'utf-8');
        // Find the table end or append
        if (content.includes('| Date | File | Issue | Owner | Status |')) {
            const lines = content.split('\n');
            const tableHeaderIndex = lines.findIndex(l => l.includes('| Date | File | Issue | Owner | Status |'));
            lines.splice(tableHeaderIndex + 2, 0, newEntry.trim());
            fs.writeFileSync(debtFilePath, lines.join('\n'));
        } else {
            fs.appendFileSync(debtFilePath, `\n${newEntry}`);
        }
        console.log(`✅ Updated DEBT.md with ${testPath}`);
    } catch (e) {
        console.error('Failed to update DEBT.md:', e);
    }
}

function quarantineTest(testPath: string) {
    const absolutePath = path.resolve(testPath);
    if (!fs.existsSync(absolutePath)) {
        console.error(`Test file not found: ${testPath}`);
        return;
    }

    const quarantineDir = path.resolve('tests/quarantine');
    if (!fs.existsSync(quarantineDir)) {
        fs.mkdirSync(quarantineDir, { recursive: true });
    }

    const targetPath = path.join(quarantineDir, path.basename(testPath));

    try {
        fs.renameSync(absolutePath, targetPath);
        console.log(`✅ Quarantined ${testPath} to ${targetPath}`);

        const prNumber = getPrNumber();
        const issueUrl = createDebtIssue(testPath, prNumber);
        if (issueUrl) {
            updateDebtFile(testPath, issueUrl);
        }
    } catch (e) {
        console.error(`Failed to quarantine ${testPath}:`, e);
    }
}

function main() {
    const args = process.argv.slice(2);
    if (args.length === 0) {
        console.log('Usage: npx tsx scripts/quarantine-test.ts <test-path>');
        return;
    }

    const testPath = args[0];
    quarantineTest(testPath);
}

main();
