// Auto-generated by src/scripts/enrich_exercise_db.ts
// Maps Hevy Exercise Names to Muscle Group, Secondaries, and Base CNS Cost (1-10)

export interface ExerciseAttributes {
    muscle: string;
    secondaryMuscles: string[];
    cnsTier: number; // 9=Critical, 7=High, 5=Med, 3=Low
}

export const EXERCISE_DB: Record<string, ExerciseAttributes> = {
  "21s Bicep Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Ab Scissors": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Ab Wheel": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Aerobics": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Air Bike": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Archer Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Arnold Press (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Around The World": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Around The World Chop": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Assisted Pistol Squats": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Back Extension (Hyperextension)": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Back Extension Iso Hold": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Back Extension (Machine)": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Back Extension (Weighted Hyperextension)": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Ball Slams": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Band Pullaparts": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Barbell Pullover": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Battle Ropes": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Behind the Back Bicep Wrist Curl (Barbell)": {
    "muscle": "forearms",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Behind the Back Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Belt Squat (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Bench Dip": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Bench Press (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Bench Press (Cable)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Bench Press - Close Grip (Barbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Bench Press (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Bench Press (Smith Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Bench Press - Wide Grip (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Bent Over Row (Band)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Bent Over Row (Barbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Bent Over Row (Dumbbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Bicep Curl (Barbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicep Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicep Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicep Curl (Machine)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicep Curl (Suspension)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicycle Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bicycle Crunch Raised Legs": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Bird Dog": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Boxing": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Box Jump": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Box Squat (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Bulgarian Split Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Burpee": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Burpee Over the Bar": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Butterfly (Pec Deck)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Cable Core Palloff Press": {
    "muscle": "abdominals",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Cable Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Cable Fly Crossovers": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Cable Pull Through": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Cable Twist (Down to up)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Cable Twist (Up to down)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Calf Extension (Machine)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Calf Press (Machine)": {
    "muscle": "calves",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Chest Dip": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Chest Dip (Assisted)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Chest Dip (Weighted)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Chest Fly (Band)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Chest Fly (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Chest Fly (Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Chest Fly (Suspension)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Chest Press (Band)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Chest Press (Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Chest Supported Incline Row (Dumbbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Chest Supported Reverse Fly (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Chest Supported Y Raise (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Chin Up": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Chin Up (Assisted)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Chin Up (Weighted)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Clamshell": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Clap Push Ups": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Clean": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Clean and Jerk": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Clean and Press": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "triceps",
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Clean Pull": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Climbing": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Concentration Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Cross Body Hammer Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Crunch (Machine)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Crunch (Weighted)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Curtsy Lunge (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Cycling": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Dead Bug": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Dead Hang": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Deadlift (Band)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Deadlift (Barbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Deadlift (Dumbbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 5
  },
  "Deadlift High Pull": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "lower_back",
      "hamstrings",
      "glutes",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Deadlift (Smith Machine)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 7
  },
  "Deadlift (Trap bar)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Decline Bench Press (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Decline Bench Press (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Decline Bench Press (Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Decline Bench Press (Smith Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Decline Chest Fly (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Decline Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Decline Crunch (Weighted)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Decline Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Diagonal Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Diamond Push Up": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Downward Dog": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Drag Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Dragon Flag": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Dragonfly": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Dumbbell Holds": {
    "muscle": "other",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Dumbbell Rear Delt Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Dumbbell Row": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Dumbbell Snatch": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 5
  },
  "Dumbbell Squeeze Press": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Dumbbell Step Up": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Elbow to Knee": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Elephant Walk": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Elliptical Trainer": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "EZ Bar Biceps Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Face Pull": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Farmers Walk": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Feet Up Bench Press (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Fire Hydrants": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Floor Press (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Floor Press (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Floor Triceps Dip": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Flutter Kicks": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Frog Jumps": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Frog Pumps (Dumbbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Front Lever Hold": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Front Lever Raise": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Front Raise (Band)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Front Raise (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Front Raise (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Front Raise (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Front Raise (Suspension)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Front Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Full Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Glute Bridge": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Glute Ham Raise": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Glute Kickback (Machine)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Glute Kickback on Floor": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Goblet Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Good Morning": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Good Morning (Barbell)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Gorilla Row (Kettlebell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Hack Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hack Squat (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hammer Curl (Band)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hammer Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hammer Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Handstand Hold": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Handstand Push Up": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Hang Clean": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Hanging Knee Raise": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hanging Leg Raise": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hang Snatch": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Heel Taps": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Helms DB Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Hex Press (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "High Knees": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "High Knee Skips": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "HIIT": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hiking": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Hip Abduction (Machine)": {
    "muscle": "abductors",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Hip Adduction (Machine)": {
    "muscle": "adductors",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Hip Thrust": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hip Thrust (Barbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hip Thrust (Machine)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hip Thrust (Smith Machine)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Hollow Rock": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Incline Bench Press (Barbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Incline Bench Press (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Incline Bench Press (Smith Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Incline Chest Fly (Dumbbell)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Incline Chest Press (Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Incline Push Ups": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Inverted Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Iso-Lateral Chest Press (Machine)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Iso-Lateral High Row (Machine)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Iso-Lateral Low Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Iso-Lateral Row (Machine)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Jack Knife Pullover": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jackknife Sit Up": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jack Knife (Suspension)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jefferson Curl": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "JM Press (Barbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jumping Jack": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jumping Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Jump Rope": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jump Shrug": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Jump Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Kettlebell Around the World": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Kettlebell Clean": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 5
  },
  "Kettlebell Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Kettlebell Goblet Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Kettlebell Halo": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Kettlebell High Pull": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Kettlebell Shoulder Press": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Kettlebell Snatch": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 5
  },
  "Kettlebell Swing": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Kettlebell Turkish Get Up": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Kipping Pull Up": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Kneeling Pulldown (band)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Kneeling Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Knee Raise Parallel Bars": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Landmine 180": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Landmine Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Landmine Squat and Press": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back",
      "triceps"
    ],
    "cnsTier": 9
  },
  "Lateral Band Walks": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Lateral Box Jump": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Lateral Leg Raises": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Lateral Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Lateral Raise (Band)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Lateral Raise (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Lateral Raise (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Lateral Raise (Machine)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Lateral Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Lat Pulldown (Band)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Lat Pulldown (Cable)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Lat Pulldown - Close Grip (Cable)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Lat Pulldown (Machine)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Leg Extension (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Leg Press Horizontal (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Leg Press (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Leg Raise Parallel Bars": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Low Cable Fly Crossovers": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Low Row (Suspension)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "L-Sit Hold": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Lunge (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Lunge (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Lying Knee Raise": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lying Leg Curl (Machine)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Lying Leg Raise": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lying Neck Curls": {
    "muscle": "neck",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lying Neck Curls (Weighted)": {
    "muscle": "neck",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lying Neck Extension": {
    "muscle": "neck",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Lying Neck Extension (Weighted)": {
    "muscle": "neck",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Meadows Rows (Barbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Mountain Climber": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Muscle Up": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Negative Pull Up": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Nordic Hamstrings Curls": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Oblique Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "One Arm Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Outer Hip Dropset": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Overhead Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Overhead Dumbbell Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Overhead Plate Raise": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Overhead Press (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Overhead Press (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Overhead Press (Smith Machine)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Overhead Squat": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Overhead Triceps Extension (Cable)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Partial Glute Bridge (Barbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Paused Flat Dumbbell Press": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Pause Squat (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Pendlay Row (Barbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Pendulum Squat (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Pike Pushup": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Pilates": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Pinwheel Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Pistol Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Plank": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Plank Pushup": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Plate Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Plate Front Raise": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Plate Press": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Plate Squeeze (Svend Press)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Power Clean": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Power Snatch": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Preacher Curl (Barbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Preacher Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Preacher Curl (Machine)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Press Under": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Pullover (Dumbbell)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Pullover (Machine)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Pull Up": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Pull Up (Assisted)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Pull Up (Band)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Pull Up (Weighted)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Push Press": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Push Up - Close Grip": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Push Up (Weighted)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Rack Pull": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Rear Delt Reverse Fly (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Rear Delt Reverse Fly (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Rear Delt Reverse Fly (Machine)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Rear Kick (Machine)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Renegade Row (Dumbbell)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Reverse Crunch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Reverse Curl (Barbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Reverse Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Reverse Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Reverse Fly Single Arm (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Reverse Grip Concentration Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Reverse Grip Lat Pulldown (Cable)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Reverse Hyperextension": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Reverse Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Reverse Lunge (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Reverse Lunge (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Reverse Plank": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Ring Dips": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 7
  },
  "Ring Pull Up": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Ring Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Romanian Deadlift (Barbell)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Romanian Deadlift (Dumbbell)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 5
  },
  "Rope Cable Curl": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Rope Straight Arm Pulldown": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Rotational Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Rowing Machine": {
    "muscle": "cardio",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Running": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Russian Twist (Bodyweight)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Russian Twist (Weighted)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Scapular Pull-Up": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 3
  },
  "Scapular Pull Ups": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Seated Cable Row - Bar Grip": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Seated Cable Row - Bar Wide Grip": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Seated Cable Row - V Grip (Cable)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Seated Calf Raise": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Seated Chest Flys (Cable)": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Seated Dip Machine": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Seated Good Morning": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Seated Incline Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Seated Lateral Raise (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Seated Leg Curl (Machine)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Seated Overhead Press (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Seated Overhead Press (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Seated Palms Up Wrist Curl": {
    "muscle": "forearms",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Seated Row (Machine)": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Seated Shoulder Press (Machine)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Seated Triceps Press": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Seated Wrist Extension (Barbell)": {
    "muscle": "forearms",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Short Range Contractions": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Shoulder Press (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Shoulder Press (Machine Plates)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Shoulder Taps": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Shrug (Barbell)": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Shrug (Cable)": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Shrug (Dumbbell)": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Shrug (Machine)": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Shrug (Smith Machine)": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Side Bend": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Side Bend (Dumbbell)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Side Plank": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Arm Cable Crossover": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Single Arm Cable Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Single Arm Curl (Cable)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Arm Landmine Press (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 5
  },
  "Single Arm Lateral Raise (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 3
  },
  "Single Arm Lat Pulldown": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Single Arm Tricep Extension (Dumbbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Arm Triceps Pushdown (Cable)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Leg Extensions": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Single Leg Glute Bridge": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Single Leg Hip Thrust": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Single Leg Hip Thrust (Dumbbell)": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Single Leg Press (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Single Leg Romanian Deadlift (Barbell)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Single Leg Romanian Deadlift (Dumbbell)": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 5
  },
  "Single Leg Standing Calf Raise": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Leg Standing Calf Raise (Barbell)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Leg Standing Calf Raise (Dumbbell)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Single Leg Standing Calf Raise (Machine)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Sissy Squat (Weighted)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Sit Up": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Sit Up (Weighted)": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Skating": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Skiing": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Skullcrusher (Barbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Skullcrusher (Dumbbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Sled Push": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Snatch": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 9
  },
  "Snowboarding": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Spider Curl (Barbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Spider Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Spiderman": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Spinning": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Split Jerk": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Split Squat (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Split Squat Hold": {
    "muscle": "lower_back",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Sprints": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Squat (Band)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Squat (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Squat (Bodyweight)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Squat (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Squat (Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Squat Row": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back",
      "biceps",
      "shoulders"
    ],
    "cnsTier": 9
  },
  "Squat (Smith Machine)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 7
  },
  "Squat (Suspension)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Staggered Push Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 5
  },
  "Stair Machine (Floors)": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Stair Machine (Steps)": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Standing Cable Glute Kickbacks": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Standing Calf Raise": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Standing Calf Raise (Barbell)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Standing Calf Raise (Dumbbell)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Standing Calf Raise (Machine)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Standing Calf Raise (Smith)": {
    "muscle": "calves",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Standing Leg Curls": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back"
    ],
    "cnsTier": 3
  },
  "Standing Military Press (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps"
    ],
    "cnsTier": 7
  },
  "Step Up": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Sternum Pull up (Gironda)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Straight Arm Lat Pulldown (Cable)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "Straight Leg Deadlift": {
    "muscle": "hamstrings",
    "secondaryMuscles": [
      "glutes",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Stretching": {
    "muscle": "other",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Sumo Deadlift": {
    "muscle": "glutes",
    "secondaryMuscles": [
      "hamstrings",
      "lower_back",
      "forearms",
      "traps"
    ],
    "cnsTier": 9
  },
  "Sumo Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Sumo Squat (Barbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Sumo Squat (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Sumo Squat (Kettlebell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 5
  },
  "Superman": {
    "muscle": "lower_back",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Swimming": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "T Bar Row": {
    "muscle": "upper_back",
    "secondaryMuscles": [
      "biceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Thruster (Barbell)": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 3
  },
  "Thruster (Kettlebell)": {
    "muscle": "full_body",
    "secondaryMuscles": [
      "shoulders",
      "glutes",
      "quadriceps"
    ],
    "cnsTier": 5
  },
  "Toes to Bar": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Toe Touch": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Torso Rotation": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Trap-3 Raise": {
    "muscle": "traps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Treadmill": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Dip": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Triceps Dip (Assisted)": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Triceps Dip (Weighted)": {
    "muscle": "triceps",
    "secondaryMuscles": [
      "chest"
    ],
    "cnsTier": 7
  },
  "Triceps Extension (Barbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Extension (Cable)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Extension (Dumbbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Extension (Machine)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Extension (Suspension)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Kickback (Cable)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Kickback (Dumbbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Pressdown": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Pushdown": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Triceps Rope Pushdown": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Upright Row (Barbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps",
      "biceps"
    ],
    "cnsTier": 3
  },
  "Upright Row (Cable)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps",
      "biceps"
    ],
    "cnsTier": 5
  },
  "Upright Row (Dumbbell)": {
    "muscle": "shoulders",
    "secondaryMuscles": [
      "triceps",
      "biceps"
    ],
    "cnsTier": 5
  },
  "Vertical Traction (Machine)": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 5
  },
  "V Up": {
    "muscle": "abdominals",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Waiter Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Walking": {
    "muscle": "cardio",
    "secondaryMuscles": [],
    "cnsTier": 7
  },
  "Walking Lunge": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Walking Lunge (Dumbbell)": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 7
  },
  "Wall Ball": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Wall Sit": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings"
    ],
    "cnsTier": 3
  },
  "Warm Up": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Wide-Elbow Triceps Press (Dumbbell)": {
    "muscle": "triceps",
    "secondaryMuscles": [],
    "cnsTier": 5
  },
  "Wide Pull Up": {
    "muscle": "lats",
    "secondaryMuscles": [
      "biceps"
    ],
    "cnsTier": 7
  },
  "Wide Push-Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Wide-to-Close Push-Up": {
    "muscle": "chest",
    "secondaryMuscles": [
      "triceps",
      "shoulders"
    ],
    "cnsTier": 3
  },
  "Wrist Roller": {
    "muscle": "forearms",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Yoga": {
    "muscle": "full_body",
    "secondaryMuscles": [],
    "cnsTier": 3
  },
  "Zercher Squat": {
    "muscle": "quadriceps",
    "secondaryMuscles": [
      "glutes",
      "hamstrings",
      "lower_back"
    ],
    "cnsTier": 9
  },
  "Zottman Curl (Dumbbell)": {
    "muscle": "biceps",
    "secondaryMuscles": [],
    "cnsTier": 3
  }
};